version: '2'
services:
    deepstream-search-provider:
        image: deepstreamio/provider-search-rethinkdb:latest
        environment:
            - DEEPSTREAM_HOST=deepstream
            - DEEPSTREAM_PORT=6020
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream
        container_name: "search-provider"
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        container_name: "redis"
    rethinkdb:
        image: rethinkdb:latest
        ports:
            - "28015:28015"
            - "8080:8080"
        volumes:
            - ./rethinkdb_data:/data/rethinkdb_data
        container_name: "rethinkdb"
    deepstream:
        build: "."
        ports:
            - "6020:6020"
            - "6021:6021"
        depends_on:
            - redis
            - rethinkdb
        container_name: "deepstream"
